### ISSUE TITLE
Uncaught (in promise) Error using classfield with a new vite lit-ts project

### ISSUE THREAD

**Issue by lukaskoeller** [open-wc/form-participation#14]
## Reproducing
When I set up a new [vite project](https://vitejs.dev/guide/#scaffolding-your-first-vite-project) using the `lit-ts` template, and using [this component](https://webcomponents.dev/edit/r15g01ZX55qiwh7Colom/src/index.ts?p=stories) while installing `@open-wc/form-control` I am getting the following error.

🐛 **[Reproduced Error Demo](https://stackblitz.com/edit/vitejs-vite-vrg6bx?devtoolsheight=33&file=src/my-element.ts)**

## Error
```
Uncaught (in promise) Error: The following properties on element fd-input will not trigger updates as expected because they are set using class fields: value. Native class fields and some compiled output will overwrite accessors used for detecting changes. See https://lit.dev/msg/class-field-shadowing for more information.
    at Input.performUpdate (reactive-element.ts:1275:17)
    at Input.scheduleUpdate (reactive-element.ts:1234:17)
    at Input.__enqueueUpdate (reactive-element.ts:1206:25)
```

## Expected Behavior
The component works just fine as it does in this [Demo](https://webcomponents.dev/edit/r15g01ZX55qiwh7Colom/src/index.ts?p=stories)

## Actual Behavior
The app is just showing nothing instead and throws the above mentioned error
<img width="221" alt="Screenshot 2022-03-08 at 22 50 22" src="https://user-images.githubusercontent.com/10390627/157331350-d60a9901-27b9-4ffe-b4a7-12d4a4c8eb6b.png">

**Comment by calebdwilliams** [comment]
Hey @lukaskoeller the API has changed a little bit for the mixin but this shouldn't be a problem any more. Can you confirm so we can close this issue?

**Comment by calebdwilliams** [comment]
Closing this issue as inactive.
