### ISSUE TITLE
`@open-wc/form-control` package not published as ESM module

### ISSUE THREAD

**Issue by hrmcdonald** [open-wc/form-participation#42]
All of the other `@open-wc` packages we leverage are published with the `"type": "module"` package.json configuration. Is there any reason why `@open-wc/form-control` specifically is not considering `@open-wc/form-helpers` is? It has just caused some strange build errors that might prevent us from leveraging it.

**Comment by calebdwilliams** [comment]
Nope. No reason. I’ll take care of this soon.
