### ISSUE TITLE
FormControlMixin causes build failures on server/Lit SSR

### ISSUE THREAD

**Issue by hrmcdonald** [open-wc/form-participation#48]
The calls to [addEventListeners in the element's constructor](https://github.com/open-wc/form-participation/blob/dcbffee5799f7fbeb428fb3e2be4f0b879ce7969/packages/form-control/src/FormControlMixin.ts#L205) break Lit SSR compatibility.

Could these be moved to the `connectedCallback`?

```typescript
connectedCallback() {
  super.connectedCallback();

  this.addEventListener?.('focus', this.#onFocus);
  this.addEventListener?.('blur', this.#onBlur);
  this.addEventListener?.('invalid', this.#onInvalid);
}
```

Alternatively, perhaps provide a method we can override to inform the mixin if it is being rendered on a server at the moment but in a library agnostic way:

```typescript
protected isServer() {
  return false;
}

constructor(...args: any[]) {
  super(...args);

  if (!this.isServer()) {
    this.addEventListener?.('focus', this.#onFocus);
    this.addEventListener?.('blur', this.#onBlur);
    this.addEventListener?.('invalid', this.#onInvalid);
  }
  this.setValue(null);
}
```

So then in a Lit element we could just override:

```typescript
import {isServer} from 'lit';

// ...

  protected isServer() {
    return isServer;
  }
```

**Comment by hrmcdonald** [comment]
Any thoughts on this @calebdwilliams ? We'd be happy to put in a PR for either direction.

**Comment by calebdwilliams** [comment]
We probably don’t need the is server. Just the optional chaining. Happy to accept that PR; more so if there’s a basic test using `@lit-labs/testing`.

**Comment by hrmcdonald** [comment]
Ah, yup, that makes way more sense. We'll look into getting something added soon.

**Comment by calebdwilliams** [comment]
@hrmcdonald I believe this should be resolved, can you confirm?

**Comment by hrmcdonald** [comment]
Yes, this is working for us now! You can close.
